version: '3'
services:
  db:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
